#ifndef SIGNAL_PATTERNS_H
#define SIGNAL_PATTERNS_H

#include <Arduino.h>
#include <avr/pgmspace.h>
#include <defs.h>
#include <signal_engine.h>

static const uint8_t CMP_TABLE_EMPTY[CMP_TABLE_BYTES] PROGMEM = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t CMP_TABLE_POLO_60_2_HALL[CMP_TABLE_BYTES] PROGMEM = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x08, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t CMP_TABLE_SAVEIRO_60_2_HALL[CMP_TABLE_BYTES] PROGMEM = {
    0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10,
    0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x02, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x20, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10,
    0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x02, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x20, 0x00, 0x40, 0x00,
    0x80, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10,
    0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x02, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x20, 0x00, 0x00, 0x00,
};

static const uint8_t CMP_TABLE_FPT_CURSOR_60_2_INDUCTIVE[CMP_TABLE_BYTES] PROGMEM = {
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00,
};

static const uint8_t CMP_TABLE_EDC16C9_60_2_HALL[CMP_TABLE_BYTES] PROGMEM = {
    0x00, 0x00, 0x00, 0x80, 0x01, 0x00, 0x00, 0x00, 0x20, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x08, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x10, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00,
    0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04,
};

struct SignalPattern {
  PGM_P name;
  CkpConfig ckp;
  CmpConfig cmp;
};

static const char SIGNAL_PATTERN_NAME_BOSCH_60_2_HALL[] PROGMEM = "60-2 Hall";
static const char SIGNAL_PATTERN_NAME_BOSCH_60_2_INDUCTIVE[] PROGMEM = "60-2 Indutivo";
static const char SIGNAL_PATTERN_NAME_44_4_HALL[] PROGMEM = "44-4 Hall";
static const char SIGNAL_PATTERN_NAME_44_4_INDUCTIVE[] PROGMEM = "44-4 Indutivo";
static const char SIGNAL_PATTERN_NAME_36_1_HALL[] PROGMEM = "36-1 Hall";
static const char SIGNAL_PATTERN_NAME_36_1_INDUCTIVE[] PROGMEM = "36-1 Indutivo";
static const char SIGNAL_PATTERN_NAME_VOLVO_18_2_X3_HALL[] PROGMEM = "Volvo 18-2x3";
static const char SIGNAL_PATTERN_NAME_POLO_60_2_HALL_CMP[] PROGMEM = "Polo 1.6";
static const char SIGNAL_PATTERN_NAME_SAVEIRO_60_2_HALL_CMP[] PROGMEM = "Saveiro 1.6";
static const char SIGNAL_PATTERN_NAME_EDC7_C1[] PROGMEM = "EDC7-C1";
static const char SIGNAL_PATTERN_NAME_EDC7_UC31[] PROGMEM = "EDC7-UC31";
static const char SIGNAL_PATTERN_NAME_EMS[] PROGMEM = "EMS";
static const char SIGNAL_PATTERN_NAME_EDC17C31[] PROGMEM = "EDC17C31";
static const char SIGNAL_PATTERN_NAME_EDC19C31[] PROGMEM = "EDC19C31";
static const char SIGNAL_PATTERN_NAME_VW_CONST_CM850[] PROGMEM = "VW Const CM850";
static const char SIGNAL_PATTERN_NAME_ATEGO_PLD[] PROGMEM = "Atego PLD";
static const char SIGNAL_PATTERN_NAME_AXOR_PLD[] PROGMEM = "Axor PLD";
static const char SIGNAL_PATTERN_NAME_MBB_OM904[] PROGMEM = "MBB OM904";
static const char SIGNAL_PATTERN_NAME_MBB_OM906[] PROGMEM = "MBB OM906";
static const char SIGNAL_PATTERN_NAME_IVECO_TECTOR[] PROGMEM = "Iveco Tector";
static const char SIGNAL_PATTERN_NAME_IVECO_EUROCARGO[] PROGMEM = "Iveco EuroCargo";
static const char SIGNAL_PATTERN_NAME_IVECO_DAILY[] PROGMEM = "Iveco Daily";
static const char SIGNAL_PATTERN_NAME_VOLVO_VM_EDC7[] PROGMEM = "Volvo VM EDC7";
static const char SIGNAL_PATTERN_NAME_VOLVO_D12_EDC[] PROGMEM = "Volvo D12 EDC";
static const char SIGNAL_PATTERN_NAME_VOLVO_D13_EMS[] PROGMEM = "Volvo D13 EMS";
static const char SIGNAL_PATTERN_NAME_SCANIA_MS62[] PROGMEM = "Scania MS6.2";
static const char SIGNAL_PATTERN_NAME_SCANIA_HPI_S6[] PROGMEM = "Scania HPI S6";
static const char SIGNAL_PATTERN_NAME_SCANIA_DC13_EMS[] PROGMEM = "Scania DC13 EMS";
static const char SIGNAL_PATTERN_NAME_MWM_MAXXFORCE[] PROGMEM = "MWM MaxxForce";
static const char SIGNAL_PATTERN_NAME_CUMMINS_ISB_CM850[] PROGMEM = "Cummins CM850";
static const char SIGNAL_PATTERN_NAME_VW_WORKER_MWM[] PROGMEM = "VW Worker MWM";
static const char SIGNAL_PATTERN_NAME_FORD_CARGO_CUMMINS[] PROGMEM = "Ford Cargo";
static const char SIGNAL_PATTERN_NAME_INTERNATIONAL_NGD[] PROGMEM = "Inter NGD";
static const char SIGNAL_PATTERN_NAME_BOSCH_MS62[] PROGMEM = "Bosch MS6.2";
static const char SIGNAL_PATTERN_NAME_BOSCH_EDC16C8[] PROGMEM = "EDC16C8";
static const char SIGNAL_PATTERN_NAME_BOSCH_EDC16C9[] PROGMEM = "EDC16C9";
static const char SIGNAL_PATTERN_NAME_BOSCH_EDC15C6[] PROGMEM = "EDC15C6";
static const char SIGNAL_PATTERN_NAME_MOTOROLA_CM850[] PROGMEM = "Motorola CM850";
static const char SIGNAL_PATTERN_NAME_SIEMENS_SID901[] PROGMEM = "SID901";
static const char SIGNAL_PATTERN_NAME_MARELLI_TRUCK[] PROGMEM = "Marelli Truck";
static const char SIGNAL_PATTERN_NAME_FPT_CURSOR[] PROGMEM = "FPT Cursor";

static const CkpConfig CKP_CONFIG_UNCALIBRATED = {1, 1, 1, SignalOutputType::Inductive, LOW};
static const CkpConfig CKP_CONFIG_60_2_INDUCTIVE = {60, 2, 1, SignalOutputType::Inductive, LOW};
static const CmpConfig CMP_CONFIG_EMPTY_HALL = {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW};
static const CmpConfig CMP_CONFIG_EMPTY_INDUCTIVE = {SignalOutputType::Inductive, CMP_TABLE_EMPTY, LOW};
static const CmpConfig CMP_CONFIG_FPT_CURSOR_INDUCTIVE = {
    SignalOutputType::Inductive, CMP_TABLE_FPT_CURSOR_60_2_INDUCTIVE, LOW};
static const CmpConfig CMP_CONFIG_EDC16C9_HALL = {SignalOutputType::Hall, CMP_TABLE_EDC16C9_60_2_HALL, HIGH};

static const SignalPattern SIGNAL_PATTERN_BOSCH_60_2_HALL = {
    SIGNAL_PATTERN_NAME_BOSCH_60_2_HALL,
    {60, 2, 1, SignalOutputType::Hall, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_BOSCH_60_2_INDUCTIVE = {
    SIGNAL_PATTERN_NAME_BOSCH_60_2_INDUCTIVE,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_44_4_HALL = {
    SIGNAL_PATTERN_NAME_44_4_HALL,
    {44, 4, 1, SignalOutputType::Hall, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_44_4_INDUCTIVE = {
    SIGNAL_PATTERN_NAME_44_4_INDUCTIVE,
    {44, 4, 1, SignalOutputType::Inductive, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_36_1_HALL = {
    SIGNAL_PATTERN_NAME_36_1_HALL,
    {36, 1, 1, SignalOutputType::Hall, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_36_1_INDUCTIVE = {
    SIGNAL_PATTERN_NAME_36_1_INDUCTIVE,
    {36, 1, 1, SignalOutputType::Inductive, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_VOLVO_18_2_X3_HALL = {
    SIGNAL_PATTERN_NAME_VOLVO_18_2_X3_HALL,
    {20, 2, 3, SignalOutputType::Hall, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_POLO_60_2_HALL_CMP = {
    SIGNAL_PATTERN_NAME_POLO_60_2_HALL_CMP,
    {60, 2, 1, SignalOutputType::Hall, LOW},
    {SignalOutputType::Hall, CMP_TABLE_POLO_60_2_HALL, LOW},
};

static const SignalPattern SIGNAL_PATTERN_SAVEIRO_60_2_HALL_CMP = {
    SIGNAL_PATTERN_NAME_SAVEIRO_60_2_HALL_CMP,
    {60, 2, 1, SignalOutputType::Hall, LOW},
    {SignalOutputType::Hall, CMP_TABLE_SAVEIRO_60_2_HALL, LOW},
};

static const SignalPattern SIGNAL_PATTERN_EDC7_C1 = {
    SIGNAL_PATTERN_NAME_EDC7_C1,
    CKP_CONFIG_60_2_INDUCTIVE,
    {SignalOutputType::Inductive, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_EDC7_UC31 = {
    SIGNAL_PATTERN_NAME_EDC7_UC31,
    CKP_CONFIG_60_2_INDUCTIVE,
    CMP_CONFIG_FPT_CURSOR_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_EMS = {
    SIGNAL_PATTERN_NAME_EMS,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    {SignalOutputType::Inductive, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_EDC17C31 = {
    SIGNAL_PATTERN_NAME_EDC17C31,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    {SignalOutputType::Inductive, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_EDC19C31 = {
    SIGNAL_PATTERN_NAME_EDC19C31,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    {SignalOutputType::Inductive, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_VW_CONST_CM850 = {
    SIGNAL_PATTERN_NAME_VW_CONST_CM850,
    {60, 2, 1, SignalOutputType::Hall, LOW},
    {SignalOutputType::Hall, CMP_TABLE_EMPTY, LOW},
};

static const SignalPattern SIGNAL_PATTERN_ATEGO_PLD = {
    SIGNAL_PATTERN_NAME_ATEGO_PLD,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_AXOR_PLD = {
    SIGNAL_PATTERN_NAME_AXOR_PLD,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_MBB_OM904 = {
    SIGNAL_PATTERN_NAME_MBB_OM904,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_MBB_OM906 = {
    SIGNAL_PATTERN_NAME_MBB_OM906,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_IVECO_TECTOR = {
    SIGNAL_PATTERN_NAME_IVECO_TECTOR,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_IVECO_EUROCARGO = {
    SIGNAL_PATTERN_NAME_IVECO_EUROCARGO,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_IVECO_DAILY = {
    SIGNAL_PATTERN_NAME_IVECO_DAILY,
    CKP_CONFIG_60_2_INDUCTIVE,
    CMP_CONFIG_EDC16C9_HALL,
};

static const SignalPattern SIGNAL_PATTERN_VOLVO_VM_EDC7 = {
    SIGNAL_PATTERN_NAME_VOLVO_VM_EDC7,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_VOLVO_D12_EDC = {
    SIGNAL_PATTERN_NAME_VOLVO_D12_EDC,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_VOLVO_D13_EMS = {
    SIGNAL_PATTERN_NAME_VOLVO_D13_EMS,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_SCANIA_MS62 = {
    SIGNAL_PATTERN_NAME_SCANIA_MS62,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_SCANIA_HPI_S6 = {
    SIGNAL_PATTERN_NAME_SCANIA_HPI_S6,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_SCANIA_DC13_EMS = {
    SIGNAL_PATTERN_NAME_SCANIA_DC13_EMS,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_MWM_MAXXFORCE = {
    SIGNAL_PATTERN_NAME_MWM_MAXXFORCE,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_CUMMINS_ISB_CM850 = {
    SIGNAL_PATTERN_NAME_CUMMINS_ISB_CM850,
    {60, 2, 1, SignalOutputType::Hall, LOW},
    CMP_CONFIG_EMPTY_HALL,
};

static const SignalPattern SIGNAL_PATTERN_VW_WORKER_MWM = {
    SIGNAL_PATTERN_NAME_VW_WORKER_MWM,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_FORD_CARGO_CUMMINS = {
    SIGNAL_PATTERN_NAME_FORD_CARGO_CUMMINS,
    {60, 2, 1, SignalOutputType::Hall, LOW},
    CMP_CONFIG_EMPTY_HALL,
};

static const SignalPattern SIGNAL_PATTERN_INTERNATIONAL_NGD = {
    SIGNAL_PATTERN_NAME_INTERNATIONAL_NGD,
    {60, 2, 1, SignalOutputType::Inductive, LOW},
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_BOSCH_MS62 = {
    SIGNAL_PATTERN_NAME_BOSCH_MS62,
    CKP_CONFIG_60_2_INDUCTIVE,
    CMP_CONFIG_FPT_CURSOR_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_BOSCH_EDC16C8 = {
    SIGNAL_PATTERN_NAME_BOSCH_EDC16C8,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_BOSCH_EDC16C9 = {
    SIGNAL_PATTERN_NAME_BOSCH_EDC16C9,
    CKP_CONFIG_60_2_INDUCTIVE,
    CMP_CONFIG_EDC16C9_HALL,
};

static const SignalPattern SIGNAL_PATTERN_BOSCH_EDC15C6 = {
    SIGNAL_PATTERN_NAME_BOSCH_EDC15C6,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_INDUCTIVE,
};

static const SignalPattern SIGNAL_PATTERN_MOTOROLA_CM850 = {
    SIGNAL_PATTERN_NAME_MOTOROLA_CM850,
    {60, 2, 1, SignalOutputType::Hall, LOW},
    CMP_CONFIG_EMPTY_HALL,
};

static const SignalPattern SIGNAL_PATTERN_SIEMENS_SID901 = {
    SIGNAL_PATTERN_NAME_SIEMENS_SID901,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_HALL,
};

static const SignalPattern SIGNAL_PATTERN_MARELLI_TRUCK = {
    SIGNAL_PATTERN_NAME_MARELLI_TRUCK,
    CKP_CONFIG_UNCALIBRATED,
    CMP_CONFIG_EMPTY_HALL,
};

static const SignalPattern SIGNAL_PATTERN_FPT_CURSOR = {
    SIGNAL_PATTERN_NAME_FPT_CURSOR,
    CKP_CONFIG_60_2_INDUCTIVE,
    CMP_CONFIG_FPT_CURSOR_INDUCTIVE,
};

static const SignalPattern *const SIGNAL_PATTERNS[] = {
    &SIGNAL_PATTERN_BOSCH_60_2_HALL,
    &SIGNAL_PATTERN_BOSCH_60_2_INDUCTIVE,
    &SIGNAL_PATTERN_44_4_HALL,
    &SIGNAL_PATTERN_44_4_INDUCTIVE,
    &SIGNAL_PATTERN_36_1_HALL,
    &SIGNAL_PATTERN_36_1_INDUCTIVE,
    &SIGNAL_PATTERN_VOLVO_18_2_X3_HALL,
    &SIGNAL_PATTERN_POLO_60_2_HALL_CMP,
    &SIGNAL_PATTERN_SAVEIRO_60_2_HALL_CMP,
    &SIGNAL_PATTERN_EDC7_C1,
    &SIGNAL_PATTERN_EDC7_UC31,
    &SIGNAL_PATTERN_EMS,
    &SIGNAL_PATTERN_EDC17C31,
    &SIGNAL_PATTERN_EDC19C31,
    &SIGNAL_PATTERN_VW_CONST_CM850,
    &SIGNAL_PATTERN_ATEGO_PLD,
    &SIGNAL_PATTERN_AXOR_PLD,
    &SIGNAL_PATTERN_MBB_OM904,
    &SIGNAL_PATTERN_MBB_OM906,
    &SIGNAL_PATTERN_IVECO_TECTOR,
    &SIGNAL_PATTERN_IVECO_EUROCARGO,
    &SIGNAL_PATTERN_IVECO_DAILY,
    &SIGNAL_PATTERN_VOLVO_VM_EDC7,
    &SIGNAL_PATTERN_VOLVO_D12_EDC,
    &SIGNAL_PATTERN_VOLVO_D13_EMS,
    &SIGNAL_PATTERN_SCANIA_MS62,
    &SIGNAL_PATTERN_SCANIA_HPI_S6,
    &SIGNAL_PATTERN_SCANIA_DC13_EMS,
    &SIGNAL_PATTERN_MWM_MAXXFORCE,
    &SIGNAL_PATTERN_CUMMINS_ISB_CM850,
    &SIGNAL_PATTERN_VW_WORKER_MWM,
    &SIGNAL_PATTERN_FORD_CARGO_CUMMINS,
    &SIGNAL_PATTERN_INTERNATIONAL_NGD,
    &SIGNAL_PATTERN_BOSCH_MS62,
    &SIGNAL_PATTERN_BOSCH_EDC16C8,
    &SIGNAL_PATTERN_BOSCH_EDC16C9,
    &SIGNAL_PATTERN_BOSCH_EDC15C6,
    &SIGNAL_PATTERN_MOTOROLA_CM850,
    &SIGNAL_PATTERN_SIEMENS_SID901,
    &SIGNAL_PATTERN_MARELLI_TRUCK,
    &SIGNAL_PATTERN_FPT_CURSOR,
};

static const uint8_t SIGNAL_PATTERN_COUNT = sizeof(SIGNAL_PATTERNS) / sizeof(SIGNAL_PATTERNS[0]);

static const uint8_t SIGNAL_MANUFACTURER_BASICOS_MODELS[] = {0, 1, 2, 3, 4, 5};
static const uint8_t SIGNAL_MANUFACTURER_MERCEDES_MODELS[] = {15, 16, 17, 18};
static const uint8_t SIGNAL_MANUFACTURER_FIAT_MODELS[] = {21};
static const uint8_t SIGNAL_MANUFACTURER_IVECO_MODELS[] = {40, 19, 20, 21};
static const uint8_t SIGNAL_MANUFACTURER_VOLVO_MODELS[] = {6, 22, 23, 24};
static const uint8_t SIGNAL_MANUFACTURER_SCANIA_MODELS[] = {25, 26, 27};
static const uint8_t SIGNAL_MANUFACTURER_VOLKSWAGEN_MODELS[] = {14, 30, 7, 8};
static const uint8_t SIGNAL_MANUFACTURER_MWM_MODELS[] = {28, 30, 32};
static const uint8_t SIGNAL_MANUFACTURER_CUMMINS_MODELS[] = {29, 31};
static const uint8_t SIGNAL_MANUFACTURER_FORD_MODELS[] = {40, 31};
static const uint8_t SIGNAL_MANUFACTURER_INTERNATIONAL_MODELS[] = {32};
static const uint8_t SIGNAL_MANUFACTURER_BOSCH_MODELS[] = {9, 10, 33, 34, 35, 36, 12, 13};
static const uint8_t SIGNAL_MANUFACTURER_MAGNETI_MARELLI_MODELS[] = {39};
static const uint8_t SIGNAL_MANUFACTURER_MOTOROLA_MODELS[] = {37};
static const uint8_t SIGNAL_MANUFACTURER_SIEMENS_MODELS[] = {11, 38};

static const char SIGNAL_MANUFACTURER_NAME_BASICOS[] PROGMEM = "Basicos";
static const char SIGNAL_MANUFACTURER_NAME_MERCEDES[] PROGMEM = "Mercedes Benz";
static const char SIGNAL_MANUFACTURER_NAME_FIAT[] PROGMEM = "Fiat";
static const char SIGNAL_MANUFACTURER_NAME_IVECO[] PROGMEM = "Iveco";
static const char SIGNAL_MANUFACTURER_NAME_VOLVO[] PROGMEM = "Volvo";
static const char SIGNAL_MANUFACTURER_NAME_SCANIA[] PROGMEM = "Scania";
static const char SIGNAL_MANUFACTURER_NAME_VOLKSWAGEN[] PROGMEM = "Volkswagen";
static const char SIGNAL_MANUFACTURER_NAME_MWM[] PROGMEM = "MWM";
static const char SIGNAL_MANUFACTURER_NAME_CUMMINS[] PROGMEM = "Cummins";
static const char SIGNAL_MANUFACTURER_NAME_FORD[] PROGMEM = "Ford";
static const char SIGNAL_MANUFACTURER_NAME_INTERNATIONAL[] PROGMEM = "International";
static const char SIGNAL_MANUFACTURER_NAME_BOSCH[] PROGMEM = "Bosch";
static const char SIGNAL_MANUFACTURER_NAME_MAGNETI_MARELLI[] PROGMEM = "Magneti Marelli";
static const char SIGNAL_MANUFACTURER_NAME_MOTOROLA[] PROGMEM = "Motorola";
static const char SIGNAL_MANUFACTURER_NAME_SIEMENS[] PROGMEM = "Siemens";

struct SignalManufacturer {
  PGM_P name;
  const uint8_t *modelPatternIndexes;
  uint8_t modelCount;
};

static const SignalManufacturer SIGNAL_MANUFACTURERS[] = {
    {SIGNAL_MANUFACTURER_NAME_MERCEDES, SIGNAL_MANUFACTURER_MERCEDES_MODELS,
     sizeof(SIGNAL_MANUFACTURER_MERCEDES_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_FIAT, SIGNAL_MANUFACTURER_FIAT_MODELS, sizeof(SIGNAL_MANUFACTURER_FIAT_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_IVECO, SIGNAL_MANUFACTURER_IVECO_MODELS, sizeof(SIGNAL_MANUFACTURER_IVECO_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_VOLVO, SIGNAL_MANUFACTURER_VOLVO_MODELS, sizeof(SIGNAL_MANUFACTURER_VOLVO_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_SCANIA, SIGNAL_MANUFACTURER_SCANIA_MODELS, sizeof(SIGNAL_MANUFACTURER_SCANIA_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_VOLKSWAGEN, SIGNAL_MANUFACTURER_VOLKSWAGEN_MODELS,
     sizeof(SIGNAL_MANUFACTURER_VOLKSWAGEN_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_MWM, SIGNAL_MANUFACTURER_MWM_MODELS, sizeof(SIGNAL_MANUFACTURER_MWM_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_CUMMINS, SIGNAL_MANUFACTURER_CUMMINS_MODELS, sizeof(SIGNAL_MANUFACTURER_CUMMINS_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_FORD, SIGNAL_MANUFACTURER_FORD_MODELS, sizeof(SIGNAL_MANUFACTURER_FORD_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_INTERNATIONAL, SIGNAL_MANUFACTURER_INTERNATIONAL_MODELS,
     sizeof(SIGNAL_MANUFACTURER_INTERNATIONAL_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_BOSCH, SIGNAL_MANUFACTURER_BOSCH_MODELS, sizeof(SIGNAL_MANUFACTURER_BOSCH_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_MAGNETI_MARELLI, SIGNAL_MANUFACTURER_MAGNETI_MARELLI_MODELS,
     sizeof(SIGNAL_MANUFACTURER_MAGNETI_MARELLI_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_MOTOROLA, SIGNAL_MANUFACTURER_MOTOROLA_MODELS,
     sizeof(SIGNAL_MANUFACTURER_MOTOROLA_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_SIEMENS, SIGNAL_MANUFACTURER_SIEMENS_MODELS, sizeof(SIGNAL_MANUFACTURER_SIEMENS_MODELS)},
    {SIGNAL_MANUFACTURER_NAME_BASICOS, SIGNAL_MANUFACTURER_BASICOS_MODELS, sizeof(SIGNAL_MANUFACTURER_BASICOS_MODELS)},
};

static const uint8_t SIGNAL_MANUFACTURER_COUNT = sizeof(SIGNAL_MANUFACTURERS) / sizeof(SIGNAL_MANUFACTURERS[0]);

inline void applySignalPattern(SignalEngine &engine, const SignalPattern &pattern) {
  engine.configureCkp(pattern.ckp);
  engine.configureCmp(pattern.cmp);
}

#endif
