#ifndef DEFS_H
#define DEFS_H

#include <Arduino.h>

#define SERIAL_BAUD_RATE 9600

#define RPM_ANALOG_PIN A0
#define RPM_MIN_VALUE 0
#define RPM_MAX_VALUE 5000
#define RPM_UPDATE_THRESHOLD 5

#define KEYBOARD_ANALOG_PIN A1
#define KEYBOARD_DEBOUNCE_MS 40
#define ADC_REFERENCE_MILLIVOLTS 5000

#define KEYBOARD_RIGHT_THRESHOLD_MV 500
#define KEYBOARD_UP_THRESHOLD_MV 1000
#define KEYBOARD_DOWN_THRESHOLD_MV 2000
#define KEYBOARD_LEFT_THRESHOLD_MV 3000
#define KEYBOARD_SELECT_THRESHOLD_MV 4000

#define LCD_I2C_ADDRESS 0x3F
#define LCD_COLUMNS 16
#define LCD_ROWS 2

#endif
